### ISSUE TITLE
ClassCastException on certain Devices

### ISSUE THREAD

**Issue by alexhicks** [Pushwoosh/pushwoosh-android-sdk#100] opened 2018-01-31 05:06 UTC
I am getting the following exception on startup. It doesn't happen on all devices and doesn't happen in debug builds. 

```
E/Pushwoosh: Exception occurred java.lang.ClassCastException: au.com.myalarm.ifob_control.x cannot be cast to com.pushwoosh.notification.NotificationFactory
at com.pushwoosh.notification.handlers.message.user.d.b(Unknown Source)
at com.pushwoosh.notification.handlers.message.user.d.<init>(Unknown Source)
at com.pushwoosh.notification.handlers.message.user.MessageHandleChainProvider.a(Unknown Source)
at com.pushwoosh.notification.handlers.message.user.MessageHandleChainProvider.init(Unknown Source)
at com.pushwoosh.notification.d.a(Unknown Source)
at com.pushwoosh.c.h(Unknown Source)
at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1759)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1734)
at android.app.ActivityThread.installProvider(ActivityThread.java:6420)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:6012)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5951)
at android.app.ActivityThread.-wrap3(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1710)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6776)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```

In the manifest I have the following set up for the Custom Notification Factory

```
<meta-data
        android:name="com.pushwoosh.notification_factory"
        android:value="au.com.myalarm.ifob_control.MyAlarmNotificationFactory" />
<meta-data
        android:name="com.pushwoosh.notification_service_extension"
        android:value="au.com.myalarm.ifob_control.MyAlarmNotificationServiceExtension" />
```

The proguard obfuscation for the class in question is:
`au.com.myalarm.ifob_control.MessagesFragment -> au.com.myalarm.ifob_control.x`
Which is quite strange as that is not the class defined in the Manifest.

I'm using version 5.5.3. My Notification Factory class does not trigger on these devices and the default push notification style is shown.

**Comment by wfhm** [comment] 2018-03-16 11:42
Hi,

Could you please let us know whether you still experience this issue or were you able to solve it?
 
If not, please make sure that you have a correct package name specified in your project and whether you have exceptions set up in proguard for notification factories for these classes?

**Comment by alexhicks** [comment] 2018-03-19 03:02
Still experiencing this issue after upgrading to Pushwoosh 5.5.6 
I have tried changing the proguard rules to no effect.

```
E/Pushwoosh: Exception occurred java.lang.ClassCastException: au.com.myalarm.ifob_control.x cannot be cast to com.pushwoosh.notification.NotificationFactory
at com.pushwoosh.notification.handlers.message.user.e.b(Unknown Source:16)
at com.pushwoosh.notification.handlers.message.user.e.<init>(Unknown Source:9)
at com.pushwoosh.notification.handlers.message.user.MessageHandleChainProvider.a(Unknown Source:16)
at com.pushwoosh.notification.handlers.message.user.MessageHandleChainProvider.init(Unknown Source:2)
at com.pushwoosh.notification.e.a(Unknown Source:0)
at com.pushwoosh.e.h(Unknown Source:106)
at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:74)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1925)
at android.content.ContentProvider.attachInfo(ContentProvider.java:1900)
at android.app.ActivityThread.installProvider(ActivityThread.java:6572)
at android.app.ActivityThread.installContentProviders(ActivityThread.java:6127)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6037)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6938)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Using the following proguard rules

```
-keep class com.pushwoosh.** { *; }
-keep public class au.com.myalarm.ifob_control.MyAlarmNotificationServiceExtension
-keep public class au.com.myalarm.ifob_control.MyAlarmNotificationServiceExtension.** { *; }
-keep class au.com.myalarm.ifob_control.MyAlarmNotificationServiceExtension.**
-keep class au.com.myalarm.ifob_control.MyAlarmNotificationFactory
-keep class au.com.myalarm.ifob_control.MyAlarmNotificationFactory.** { *; }
-keep class au.com.myalarm.ifob_control.MyAlarmNotificationFactory.**
-dontwarn com.pushwoosh.**
```

**Comment by wfhm** [comment] 2018-03-27 13:33
@alexhicks we were unable to reproduce the issue on our side. Proguard rules seem to be set up correctly, therefore it looks like the issue is related to a mismatch of package names somewhere in your project, however we cannot say for sure where exactly.

Also, if you do not obfuscate your au.com.myalarm.ifob_control.MessagesFragment class, does the issue persist?

**Comment by wfhm** [comment] 2018-05-16 11:15
@alexhicks Are you able to reproduce the issue with the latest plugin versions?

**Comment by alexhicks** [comment] 2018-05-25 01:58
@wfhm Sorry about the late reply I lost access to the device that reliably reproduces the issue for a month. 
Yes I am using com.pushwoosh:pushwoosh:5.7.2 and getting a slightly different exception now.

```
05-25 10:54:43.279 16443-16443/? E/Pushwoosh: Exception occurred
    java.lang.IllegalAccessException: java.lang.Class<au.com.myalarm.ifob_control.x> is not accessible from java.lang.Class<com.pushwoosh.notification.handlers.message.user.e>
        at java.lang.Class.newInstance(Native Method)
        at com.pushwoosh.notification.handlers.message.user.e.b(Unknown Source:12)
        at com.pushwoosh.notification.handlers.message.user.e.<init>(Unknown Source:9)
        at com.pushwoosh.notification.handlers.message.user.MessageHandleChainProvider.a(Unknown Source:16)
        at com.pushwoosh.notification.handlers.message.user.MessageHandleChainProvider.init(Unknown Source:2)
        at com.pushwoosh.notification.e.a(Unknown Source:0)
        at com.pushwoosh.n.k(Unknown Source:113)
        at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:74)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1925)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1900)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6572)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6127)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6037)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by wfhm** [comment] 2019-02-18 10:43
@alexhicks Is this issue still reproducible with the latest SDK version?

**Comment by wfhm** [comment] 2019-03-07 05:23
Closed as outdated.

**Closed by wfhm** 2019-03-07 05:23 UTC
