### ISSUE TITLE
IllegalStateException on 8.1 devices

### ISSUE THREAD

**Issue by mukovozov** [Pushwoosh/pushwoosh-android-sdk#109] opened 2018-06-21 12:13 UTC
On android devices with version 8.1 i have crashes sometimes.
stacktrace:
`Caused by java.lang.IllegalStateException: Not allowed to start service Intent { act=com.google.android.gms.measurement.UPLOAD cmp=app/com.google.android.gms.measurement.AppMeasurementService (has extras) }: app is in background uid UidRecord{f9a1f7b u0a112 RCVR idle change:uncached procs:2 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1521)
       at android.app.ContextImpl.startService(ContextImpl.java:1477)
       at android.content.ContextWrapper.startService(ContextWrapper.java:650)
       at android.content.ContextWrapper.startService(ContextWrapper.java:650)
       at android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(WakefulBroadcastReceiver.java:99)
       at com.google.android.gms.measurement.AppMeasurementReceiver.doStartService(Unknown Source)
       at com.google.android.gms.internal.zzccn.onReceive(Unknown Source:68)
       at com.google.android.gms.measurement.AppMeasurementReceiver.onReceive(Unknown Source:13)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3187)
       at android.app.ActivityThread.-wrap17(Unknown Source)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1672)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)`

I configured firebase and gcm in my app. What is it?

**Comment by wfhm** [comment] 2018-07-03 08:41
@mukovozov 

Hi,

At the first sight it does not look directly related to Pushwoosh plugin, and we were unable to reproduce it so far, therefore may I ask you if you are aware of any additional details regarding the issue, and whether there are any clear steps to reproduce it?

**Comment by wfhm** [comment] 2018-08-16 06:43
@mukovozov any updates?

**Comment by mukovozov** [comment] 2018-08-16 07:10
No. Only pushwoosh uses wakefulBroadcastReceiver included in firebaseMessaging. I have no idea why this happened.

**Comment by wfhm** [comment] 2018-08-30 10:59
Hello @mukovozov ,

This is Android 8 default behavior. Calling `startService` while your app is in background or closed will crash your app. You can find more info here: 

https://developer.android.com/about/versions/oreo/background
https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten

Pushwoosh SDK, starting with 5.0.4 version, uses JobIntentService to wake your app in background, so could you please clarify which Pushwoosh SDK version are you using?

**Comment by wfhm** [comment] 2019-02-18 10:50
@mukovozov any news on this issue?

**Comment by wfhm** [comment] 2019-03-07 05:23
Closed as outdated. Please feel free to reach us out if there will be any news on this issue.

**Closed by wfhm** 2019-03-07 05:23 UTC
