### ISSUE TITLE
Local notifications on app update duplicate

### ISSUE THREAD

**Issue by n-belokopytov** [Pushwoosh/pushwoosh-android-sdk#84] opened 2017-11-09 15:16 UTC
Hello, judging from our metrics, on **5.4.2** the **local notifications** get duplicated when the app is updated - they are not being cleared from the Alarm Manager, when we call "clear all" before re-scheduling them. Could that be the case?

**Comment by wfhm** [comment] 2017-11-17 07:14
Hi,

Checking it.

**Comment by n-belokopytov** [comment] 2017-11-17 15:37
@wfhm additionally please check out whether you do not duplicate scheduled notifications on phone reboot

**Comment by n-belokopytov** [comment] 2017-12-12 12:42
@wfhm any news? we still receive a lot of crashes because of the local notifications on releasing a new update.

**Comment by wfhm** [comment] 2017-12-14 03:34
@n-belokopytov 

We were unable to reproduce the issue locally yet. This issue is in our pipeline, however it will most likely not be fixed with the nearest upcoming release.

**Comment by Nissshhh** [comment] 2018-09-27 12:42
hello any update on this issue.

**Comment by wfhm** [comment] 2018-10-01 10:51
@Nissshhh could you please describe the issue in a bit more details? Is it possible to provide us with the steps to reproduce it?

**Comment by wfhm** [comment] 2018-11-21 14:03
@Nissshhh any updates?

**Comment by wfhm** [comment] 2018-11-22 06:03
@Nissshhh Thank you for the feedback!

**Closed by wfhm** 2018-11-22 06:03 UTC
