### ISSUE TITLE
5.4.0 crashes app on startup

### ISSUE THREAD

**Issue by gholz** [Pushwoosh/pushwoosh-android-sdk#78] opened 2017-10-19 09:38 UTC
```
10-19 11:38:16.296 22684-22684/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.getyourguide.android.debug, PID: 22684
                                                   java.lang.RuntimeException: Unable to get provider com.pushwoosh.PushwooshInitProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:6288)
                                                       at android.app.ActivityThread.installContentProviders(ActivityThread.java:5851)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5772)
                                                       at android.app.ActivityThread.-wrap1(Unknown Source:0)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1661)
                                                       at android.os.Handler.dispatchMessage(Handler.java:105)
                                                       at android.os.Looper.loop(Looper.java:164)
                                                       at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                    Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
                                                       at com.pushwoosh.internal.platform.prefs.d.<init>(Unknown Source:12)
                                                       at com.pushwoosh.internal.platform.prefs.d.d(Unknown Source:9)
                                                       at com.pushwoosh.internal.platform.prefs.d.b(Unknown Source:4)
                                                       at com.pushwoosh.internal.platform.AndroidPlatformModule.a(Unknown Source:0)
                                                       at com.pushwoosh.internal.platform.AndroidPlatformModule.init(Unknown Source:2)
                                                       at com.pushwoosh.PushwooshInitProvider.onCreate(Unknown Source:36)
                                                       at android.content.ContentProvider.attachInfo(ContentProvider.java:1919)
                                                       at android.content.ContentProvider.attachInfo(ContentProvider.java:1894)
                                                       at android.app.ActivityThread.installProvider(ActivityThread.java:6285)
```

**Comment by wfhm** [comment] 2017-10-19 09:40
@gholz 

Thanks for reporting it! The issue is already fixed in 5.4.1.

**Closed by wfhm** 2017-10-19 09:40 UTC
