### ISSUE TITLE
NullPointerException in com.pushwoosh.inapp.InAppRetrieverService.onHandleWork in 5.5.2

### ISSUE THREAD

**Issue by lynksant** [Pushwoosh/pushwoosh-android-sdk#90] opened 2017-12-18 15:04 UTC
InAppRetrieverService started by Pushwoosh library 5.5.2 crashes with following stacktrace:

> Caused by: java.lang.ExceptionInInitializerError: 
>   at com.pushwoosh.inapp.b.c (Unknown Source)
>   at com.pushwoosh.inapp.InAppRetrieverService.onHandleWork (Unknown Source)
>   at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground (Unknown Source)
>   at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground (Unknown Source)
>   at android.os.AsyncTask$2.call (AsyncTask.java:304)
>   at java.util.concurrent.FutureTask.run (FutureTask.java:237)

> Caused by: java.lang.NullPointerException: 
>   at com.pushwoosh.internal.platform.AndroidPlatformModule.getApplicationContext (Unknown Source)
>   at com.pushwoosh.inapp.b.<clinit> (Unknown Source)

Are you aware of this issue? In case of positive answer, is there any ETA for fix?

**Comment by wfhm** [comment] 2017-12-19 13:24
Hi,

We have not received any similar reports yet. Could you please describe when exactly does this crash occur?

**Comment by lynksant** [comment] 2017-12-19 14:07
Hi @wfhm 

As far as I see from the crash it happens when onHandleWork method in job service com.pushwoosh.inapp.InAppRetrieverService is triggered. I suppose Pushwoosh performs some background processing there.

It's hard to say due to obfuscated code but I guess that issue may be in not initialized weak reference to Context in AndroidPlatformModule class.

**Comment by wfhm** [comment] 2017-12-20 09:53
Hi @lynksant 

We could not reproduce it on our side. May I ask you to share a reproducer code/apk with us? If it is by any chance possible, please send it to help@pushwoosh.com

**Comment by lynksant** [comment] 2017-12-20 14:43
Hi @wfhm 

I've sent the APK file to help@pushwoosh.com. 

As for reproducer code, I can only share obfuscated version from Pushwoosh SDK sources if you need?

**Comment by wfhm** [comment] 2017-12-21 06:25
@lynksant thanks, we are investigating it.

**Comment by GBouerat** [comment] 2018-01-03 09:46
I have hundred thousands of this NullPointerException on applications available here :
https://play.google.com/store/apps/dev?id=8528754628566512212

with the same stacktrace ...

**Comment by MixMasterRickyC** [comment] 2018-01-05 11:17
We are seeing the exact stacktrace on the Google Play Console for our application as well.

**Comment by GBouerat** [comment] 2018-01-05 15:39
`java.lang.RuntimeException: 
  at android.os.AsyncTask$3.done (AsyncTask.java:309)
  at java.util.concurrent.FutureTask.finishCompletion (FutureTask.java:354)
  at java.util.concurrent.FutureTask.setException (FutureTask.java:223)
  at java.util.concurrent.FutureTask.run (FutureTask.java:242)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
  at java.lang.Thread.run (Thread.java:818)
Caused by: java.lang.ExceptionInInitializerError: 
  at com.pushwoosh.inapp.InAppRetrieverService.onHandleWork (InAppRetrieverService.java)
  at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground$10299ca (JobIntentService.java:391)
  at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:382)
  at android.os.AsyncTask$2.call (AsyncTask.java:295)
  at java.util.concurrent.FutureTask.run (FutureTask.java:237)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
  at java.lang.Thread.run (Thread.java:818)
Caused by: java.lang.NullPointerException: 
  at com.pushwoosh.internal.platform.AndroidPlatformModule.getApplicationContext (AndroidPlatformModule.java)
  at com.pushwoosh.inapp.b.<clinit> (b.java)
  at com.pushwoosh.inapp.InAppRetrieverService.onHandleWork (InAppRetrieverService.java)
  at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground$10299ca (JobIntentService.java:391)
  at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground (JobIntentService.java:382)
  at android.os.AsyncTask$2.call (AsyncTask.java:295)
  at java.util.concurrent.FutureTask.run (FutureTask.java:237)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:588)
  at java.lang.Thread.run (Thread.java:818)`

Most of these NullPointerExceptions occurs around midnight, I suppose your InAppRetrieverService start at that time, WTF is that ?

**Comment by dvassev** [comment] 2018-01-09 21:15
I see the same issue in an application as well. About 10% of the userbase seems to be getting it. 

Any update on this?

**Comment by wfhm** [comment] 2018-01-12 11:49
@lynksant @GBouerat @MixMasterRickyC @dvassev fixed in [5.5.3](https://github.com/Pushwoosh/pushwoosh-android-sdk/tree/5.5.3)

**Closed by wfhm** 2018-01-12 11:49 UTC
