### ISSUE TITLE
Too many alarms (500) registered from uid "xxxxx"

### ISSUE THREAD

**Issue by gholz** [Pushwoosh/pushwoosh-android-sdk#66] opened 2017-09-06 12:28 UTC
Hey guys, since we updated the sdk to versions 5 and above we've been receiving this error a lot:

```
Package: com.getyourguide.android
Version Code: 241000002
Version Name: 2.41.2
Android: 7.0
Android Build: NRD90M.T820XXU1AQF3
Manufacturer: samsung
Model: SM-T820
Thread: main-1
CrashReporter Key: A43941A5-79B0-BEB4-83A4-C123E3936BB6E1736900
Start Date: Wed Aug 30 19:59:00 GMT+02:00 2017
Date: Wed Aug 30 19:59:20 GMT+02:00 2017

java.lang.SecurityException: !@Too many alarms (500) registered from uid 10171
	at android.os.Parcel.readException(Parcel.java:1693)
	at android.os.Parcel.readException(Parcel.java:1646)
	at android.app.IAlarmManager$Stub$Proxy.set(IAlarmManager.java:228)
	at android.app.AlarmManager.setImpl(AlarmManager.java:737)
	at android.app.AlarmManager.set(AlarmManager.java:390)
	at com.pushwoosh.notification.LocalNotificationReceiver.scheduleNotification(Unknown Source)
	at com.pushwoosh.notification.e.f(Unknown Source)
	at com.pushwoosh.g.a(Unknown Source)
	at com.pushwoosh.g.a(Unknown Source)
	at com.pushwoosh.j.onReceive(Unknown Source)
	at com.pushwoosh.internal.event.EventBus.b(Unknown Source)
	at com.pushwoosh.internal.event.EventBus.c(Unknown Source)
	at com.pushwoosh.internal.event.EventBus.a(Unknown Source)
	at com.pushwoosh.internal.event.c.run(Unknown Source)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6780)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```

Upon further investigation we found out it might be a common issue with some samsung devices, Firebase had a similar problem not to long ago as you can see here:
[https://groups.google.com/forum/#!topic/firebase-talk/Q_zycHnTGu0](url)

Another issue that I'm not sure if it's related to this is that some of our users are receiving to manny notifications for the same thing.

**Comment by wfhm** [comment] 2017-09-07 13:17
Duplicate of https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/61.

**Comment by gholz** [comment] 2017-09-07 16:05
I'll complement that one

**Closed** 2017-09-08 08:15 UTC
