### ISSUE TITLE
NullPointerException for proguard-rules

### ISSUE THREAD

**Issue by pashko00710** [Pushwoosh/pushwoosh-android-sdk#108] opened 2018-03-30 15:21 UTC
**Good afternoon.**

In a release build, such an exception flies. 
The proguard contains all the necessary rules. An example from below:

```
-keep class com.pushwoosh.** { *; }
-keep class com.arellomobile.** { *; }
-dontwarn com.pushwoosh.**
-dontwarn com.arellomobile.**
```
**Exception:**
```
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'com.pushwoosh.internal.preference.PreferenceBooleanValue com.pushwoosh.a.h.a()' on a null object reference

Fatal Exception: java.lang.RuntimeExceptionUnable to create application ru.ideast.championat.presentation.App: java.lang.NullPointerException: Attempt to invoke virtual method 'com.pushwoosh.internal.preference.PreferenceBooleanValue com.pushwoosh.a.h.a()' on a null object reference Raw Text
--
  | android.app.ActivityThread.handleBindApplication (ActivityThread.java:4987)
  | com.android.internal.os.ZygoteInit.main (ZygoteInit.java:768)


```
Full stacktrace by the link below:
[https://fotki.yandex.ru/next/users/pashko00710/album/568905/view/1528173](https://fotki.yandex.ru/next/users/pashko00710/album/568905/view/1528173)
I will add. Drops on the line (without it works):
`PushwooshNotificationSettings.setMultiNotificationMode(true);`

In advance thanks for the answer. 
I probably torture you with questions =)

**Comment by wfhm** [comment] 2018-04-03 09:20
Hi,

Checking it.

**Comment by wfhm** [comment] 2018-04-03 10:34
@pashko00710 

`PushwooshNotificationSettings` class objects can only be used in the main process of your app. If you use it outside of the main Pushwoosh class, it will lead to NPE. Do you have any services in your app running in a separate process?

**Comment by pashko00710** [comment] 2018-04-03 12:20
No. This class is called in the onCreate method of Application.

**Comment by wfhm** [comment] 2018-04-04 11:13
@pashko00710 

> Is this error visible because of other dependencies?

It shouldn't be the case. 

To prevent these errors in future, with the next release `PushwooshNotificationSettings` will be added with a few modifications.

**Comment by pashko00710** [comment] 2018-04-04 12:01
@wfhm 

Thanks for the help! 

I will wait new release.

**Comment by wfhm** [comment] 2018-04-05 12:10
@pashko00710 Fixed in 5.5.9.

**Comment by pashko00710** [comment] 2018-04-05 13:07
Now PushwooshNotificationSettings.setMultiNotificationMode (true); works the same as with the parameter false.

**Comment by wfhm** [comment] 2018-04-23 18:47
@pashko00710 

Still could not reproduce the issue on our side. Did you try installing it on a clean device or clearing device cache, cleaning your build and reinstalling it on your test device?

**Comment by pashko00710** [comment] 2018-08-01 07:28
Good day!

I apologize for such a long absence, but my mistake is still relevant. 

What assembly do you need to send a test or combat?

**Comment by wfhm** [comment] 2018-08-01 12:55
@pashko00710 

By any chance could you please share a simple project reproducing this issue (by forking [our Sample app](https://github.com/Pushwoosh/pushwoosh-android-sdk/tree/master/Samples/Android-Advanced) or sending it to help@pushwoosh.com with a reference to this thread?

It would be an ideal solution, however, alternatively, you can also share an apk assembled with a debug configuration.

**Closed** 2019-02-18 10:44 UTC
