### ISSUE TITLE
Rich Media Push not displayed correctly

### ISSUE THREAD

**Issue by EstebanC02** [Pushwoosh/pushwoosh-android-sdk#112] opened 2018-07-29 18:55 UTC
On a HUAWEI Y520-U03
Android Version: 4.4.2

The Rich Media Push is displayed very low down and requires the user to slide the screen.

![device-2018-07-29-133856](https://user-images.githubusercontent.com/11792308/43369636-fb9f7e00-9336-11e8-831f-2093be4639cb.png)

**Comment by wfhm** [comment] 2018-08-20 05:45
@EstebanC02 Hey,

By any chance could you please try reproducing the issue with our [Sample app](https://github.com/Pushwoosh/pushwoosh-android-sdk/tree/master/Samples/Android-Advanced) and let us know if it is reproducible with it and whether any other devices have the same behavior?

**Comment by wfhm** [comment] 2018-08-30 11:04
@EstebanC02 got it reproduced. This behavior seems to be related to Android 4 only and will be fixed with the next release.

**Comment by wfhm** [comment] 2018-10-10 08:16
@EstebanC02 Finally fixed it on Pushwoosh backend, so no SDK update is required.

**Closed by wfhm** 2018-10-10 08:16 UTC
