### ISSUE TITLE
Cancel a local notification with local id

### ISSUE THREAD

**Issue by katepratik** [Pushwoosh/pushwoosh-android-sdk#51] opened 2017-01-20 14:16 UTC
After showing a local notification i want to cancel it at a particular action. 
So how i tried to retrieve local id of the push notification generated locally. But i tried below code

`NotificationManager nMgr = (NotificationManager) getSystemService(ns);
nMgr.cancel(local_push_id);` 

It didn't work for me as the ids were different

Hence i had to find a work around 

`ArrayList<String> arrayList = PushManager.getInstance(getContext()).getPushHistory();
                JSONObject lastNotification = new JSONObject(arrayList.get(arrayList.size()-1));
                int message_id = lastNotification.getInt("message_id");`

Now i get last message_id from above code. But u need to have a function which gives us the message_id
directly.

Also u need to give us a direct way to clear a particular notification by local id.

**Comment by wfhm** [comment] 2017-01-30 12:20
Hi,

We've already put it in our pipeline, the described methods to return `message_id` and to clear a a particular notifications will be added in the next major release of Pushwoosh Android SDK.

**Comment by katepratik** [comment] 2017-01-30 12:31
Cool, its great to hear that you have it in pipeline. Looking forward to replace my long code fix with your method calls.

**Comment by n-belokopytov** [comment] 2017-02-23 15:01
@wfhm hello, is the method implemented at this point? The issue is still open. Also can you tell me the following:

1) Will scheduled local notifications still be sent if the main app is closed for whatever reason?
2) Will scheduled local notifications remain scheduled upon a restart of the device?

Thank you!

**Comment by wfhm** [comment] 2017-02-27 13:42
@n-belokopytov Hi, the method is not yet implemented.

> Will scheduled local notifications still be sent if the main app is closed for whatever reason?

Yes, it will be sent to both backgrounded and swiped from task manager alike, however force stopped apps will not receive it.

> Will scheduled local notifications remain scheduled upon a restart of the device?

Same here, a notification will be shown even after device is restarted.

**Comment by wfhm** [comment] 2019-02-18 10:40
Closed as outdated. Please contact us if it needs to be reopened.

**Closed by wfhm** 2019-02-18 10:40 UTC
