### ISSUE TITLE
java.lang.NullPointerException in getPushEventListener

### ISSUE THREAD

**Issue by JulienPalard** [Pushwoosh/pushwoosh-android-sdk#12] opened 2015-06-05 10:42 UTC
o/

I'm getting a null pointer exception while trying pushwoosh:

```
E/AndroidRuntime(17744): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
E/AndroidRuntime(17744): 	at com.arellomobile.android.push.fragment.PushFragment.getPushEventListener(Unknown Source)
E/AndroidRuntime(17744): 	at com.arellomobile.android.push.fragment.PushFragment.checkMessage(Unknown Source)
E/AndroidRuntime(17744): 	at com.arellomobile.android.push.fragment.PushFragment.access$000(Unknown Source)
E/AndroidRuntime(17744): 	at com.arellomobile.android.push.fragment.PushFragment$1.onRegisterActionReceive(Unknown Source)
E/AndroidRuntime(17744): 	at com.arellomobile.android.push.utils.RegisterBroadcastReceiver.onReceive(Unknown Source)
E/AndroidRuntime(17744): 	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:866)
E/AndroidRuntime(17744): 	... 8 more
```

I simply followed the `Fragment` documentation, registered my device as a test one, and sent a push.

App crash at startup, I have absolutely no idea on how to debug this as I only see arellomobile code in my stacktrace.

**Comment by shaders** [comment] 2015-06-08 18:37
Hi,

Did you invoke init method in the onCreate method of PushFragment's parent activity?

The crash you receive is because activity in the fragment is not initialised.

**Comment by JulienPalard** [comment] 2015-06-08 19:30
Yes I'm calling `PushFragment.init(this);` in my `protected void onCreate(final Bundle savedInstanceState)` from my `LAUNCHER` activity.

My launcher activity is a class inheriting from a class itself inheriting from `ActionBarActivity`.

To confirm this I tried to break on the call, and the break happen.

I even got the "doOnRegistered" call:

```
D/mdk/push( 6245): onRegistered(A***redacted***)
***redacted***
D/AndroidRuntime( 6245): Shutting down VM
E/AndroidRuntime( 6245): FATAL EXCEPTION: main
E/AndroidRuntime( 6245): Process: fr.mandark.www, PID: 6245
E/AndroidRuntime( 6245): java.lang.RuntimeException: Error receiving broadcast Intent { act=fr.mandark.www.com.arellomobile.android.push.REGISTER_BROAD_CAST_ACTION flg=0x10 pkg=fr.mandark.www (has extras) } in com.arellomobile.android.push.fragment.PushFragment$1@2a3f0a8c
[...]
```

Tell me if I can provide more information about this one.

**Comment by shaders** [comment] 2015-06-22 11:03
Do you have a simple sample code to reproduce the issue?

**Comment by JulienPalard** [comment] 2015-06-23 07:48
No, sry :-( Yet I think you should check for this null reference, and log something verbose instead of crashing ? That may be the better that we can do about this as I don't have more information about it :(

**Comment by shaders** [comment] 2015-06-26 12:13
fixed in next update

**Closed by shaders** 2015-06-26 12:13 UTC
