### ISSUE TITLE
AbsNotificationFactory::onGenerateNotification

### ISSUE THREAD

**Issue by JulienPalard** [Pushwoosh/pushwoosh-android-sdk#23] opened 2015-10-30 16:54 UTC
I'm trying to generate my own notifications using AbsNotificationFactory::onGenerateNotificaion, but I have some problems:

 - The code is executed, but the returned notification is only displayed a few milliseconds. (If I run the same notificationbuilder code myself, and calling `notify` from the manager myself, outside pushwoosh environment, the notification is right). Also, `doOnMessageReceive` is called just after `onGenerateNotification`.

 - When the app is closed, `onGenerateNotification(PushData)` is not called. A notification appear, but obviously without the modification of onGenerateNotification.

**Comment by JulienPalard** [comment] 2015-10-30 17:05
I tried to copy/paste `onGenerateNotification`, from the [sample](https://github.com/Pushwoosh/pushwoosh-native-samples/blob/master/Android/src/com/pushwoosh/test/tags/sample/app/NotificationFactorySample.java), exact same effect (notification blinks a few milliseconds). Also, some methods used in the example does not exists. (But I successfully found the new names).

**Comment by shaders** [comment] 2015-11-03 21:22
It looks like you using push message receiver. This way you won't see notification when the app is active.
Make sure to unregister it in in onPause function!

https://github.com/Pushwoosh/pushwoosh-native-samples/blob/master/Android/src/com/pushwoosh/test/tags/sample/app/MainActivity.java

	private BroadcastReceiver mReceiver = new BasePushMessageReceiver()
	{
		@Override
		protected void onMessageReceive(Intent intent)
		{
			//JSON_DATA_KEY contains JSON payload of push notification.
			doOnMessageReceive(intent.getExtras().getString(JSON_DATA_KEY));
		}
	};

What's happening under the hood is this receiver will redirect the notification to the app and cancels the notification from the NotificationManager.

Take also a look here:
http://docs.pushwoosh.com/docs/android-faq#customizing-push-notifications

You have to call:
    pushManager.setNotificationFactory(new NotificationFactorySample());

Your factory class will be created when the app is closed using class name reflection.

**Comment by JulienPalard** [comment] 2015-11-04 13:45
It don't look like I'm using a push message receiver.

What I think I want for the moment is: Always pass thru my NotificationFactory.

What I've done:

 - Implement PushEventListener in my main activity following the tuto
 - call `PushFragment.init(this);` in onCreate()
 - call `PushManager.getInstance(this).setNotificationFactory(new PushNotificationFactory(this));` right after `PushFragment.init(this);`
 - Overwriten `onNewIntent` calling `PushFragment.onNewIntent`
 - Implemented mandatory method due to `PushEventListener` (Sending `.getPushwooshHWID(this)` and `registrationId` to my backend) in `doOnRegistered`, logging in other methods.
 - implemented my `PushNotificationFactory extends AbsNotificationFactory` with a `onGenerateNotification` returning a `Notification`.
 - Modified my Manifest in order to add what's needed according to the doc

And that's it I have the two problems already stated in my first message.

**Comment by shaders** [comment] 2015-11-09 13:33
Any chance you could share sample project to reproduce the behavior?

**Comment by shaders** [comment] 2015-11-09 13:49
1. (Also, doOnMessageReceive is called just after onGenerateNotification.) - this is the pattern when you receive push in foreground app. Notification is canceled and the push is delivered to your app. This is default behavior with Fragments at the moment. Do you want to keep the notification? Do you want doOnMessageReceive function to be called?

2. Make sure your notification factory has default public constructor. Basically it will be instantiated using this code:

			String notificationFactoryClassName = NotificationPrefs.getNotificationFactoryClassName(context);
			Class<?> notificationFactoryClass = Class.forName(notificationFactoryClassName);
			
			factory = (AbsNotificationFactory) notificationFactoryClass.newInstance();


And this code might be an issue (your factory takes parameter):

			new PushNotificationFactory(this)

**Closed** 2016-01-19 11:03 UTC
