### ISSUE TITLE
Espresso Idling Resources again

### ISSUE THREAD

**Issue by dyadischevma** [Pushwoosh/pushwoosh-android-sdk#147] opened 2020-11-12 07:07 UTC
Hello! 
Our app uses pushwoosh sdk 5.22.1.
I'm writing UI tests with Espresso. Suddenly, the tests started throwing an error:
androidx.test.espresso.AppNotIdleException: Looped for 7 iterations over 60 SECONDS. The following Idle Conditions failed ASYNC_TASKS_HAVE_IDLED.
I dumped threads and found working asynctasks, that blocks Espresso:

`"AsyncTask #2@19710" prio=5 tid=0x214 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at libcore.io.Linux.connect(Linux.java:-1)
	  at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:118)
	  at libcore.io.IoBridge.connectErrno(IoBridge.java:151)
	  at libcore.io.IoBridge.connect(IoBridge.java:129)
	  at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
	  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
	  - locked <0x4d02> (a java.net.SocksSocketImpl)
	  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
	  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
	  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
	  at java.net.Socket.connect(Socket.java:621)
	  at com.android.okhttp.internal.Platform.connectSocket(Platform.java:145)
	  at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
	  at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
	  at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
	  at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	  at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
	  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
	  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
	  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:258)
	  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:26)
	  at com.google.firebase.perf.network.zzf.getOutputStream(com.google.firebase:firebase-perf@@19.0.7:67)
	  at com.google.firebase.perf.network.zzc.getOutputStream(com.google.firebase:firebase-perf@@19.0.7:13)
	  at com.pushwoosh.internal.network.e.a(Unknown Source:-1)
	  at com.pushwoosh.internal.network.e.a(Unknown Source:-1)
	  at com.pushwoosh.internal.network.e.a(Unknown Source:-1)
	  at com.pushwoosh.internal.network.e$b.a(Unknown Source:-1)
	  at com.pushwoosh.internal.network.e$b.doInBackground(Unknown Source:-1)
	  at android.os.AsyncTask$2.call(AsyncTask.java:333)
	  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	  at java.lang.Thread.run(Thread.java:764)`

Then I found a closed issue https://github.com/Pushwoosh/pushwoosh-android-sdk/issues/104 .
I tried to change pushwoosh version, but tests still fail. A few days ago tests worked fine. How can I fix it?

**Comment by wfhm** [comment] 2020-11-13 07:10
@dyadischevma Hey,

Could you please elaborate on this issue? Is it by any chance possible for you to share a simple reproducer project with the test that fails so we could check what is happening on our side?

**Comment by dyadischevma** [comment] 2020-11-13 09:49
Yep, I created a simple project, which based on pushwoosh sample: https://github.com/dyadischevma/pushwoosh-reproduce . Tests don't crash on it, but a button click takes about 30 seconds, which is a lot. Unfortunately, on such a simple project, I can't achieve constant reproduce, this happens about half of the time. And when I dumped it, I saw asynktasks again.

**Comment by wfhm** [comment] 2020-11-17 08:16
@dyadischevma,

It looks like it is happening when establishing a connection to our backend. Last week we have had issues that could have caused temporary performance degradation for some of our clients, resulting in API timeouts that could explain idling of async tasks. I have run tests in your test app like 50 times and right now it seems to be working fine, the longest run took less than 3 seconds. Could you please confirm that it is working fine on your end now?

**Comment by dyadischevma** [comment] 2020-11-18 06:28
@wfhm,
It really looks like problems with a connection. I greped logs by "pushwoosh" and saw this log:
`2020-11-18 09:18:44.020 4717-4798/ru.ozon.delivery.debug D/Pushwoosh: [CrashAnalytics] Looking for exceptions in: /data/user/0/ru.ozon.delivery.debug/files
2020-11-18 09:18:44.176 4717-4717/ru.ozon.delivery.debug I/Pushwoosh: Log level: DEBUG
2020-11-18 09:18:44.186 4717-4717/ru.ozon.delivery.debug I/Pushwoosh: [NotificationManager] Sender ID: 902901809150
2020-11-18 09:18:44.187 4717-4717/ru.ozon.delivery.debug I/Pushwoosh: [NotificationManager] App ID: AAAFF-F8D8B
2020-11-18 09:18:44.188 4717-4717/ru.ozon.delivery.debug D/Pushwoosh: initHwid
2020-11-18 09:18:44.190 4717-4717/ru.ozon.delivery.debug I/Pushwoosh: HWID: 
2020-11-18 09:18:44.190 4717-4717/ru.ozon.delivery.debug D/Pushwoosh: [PushwooshModule] onApplicationCreated
2020-11-18 09:18:44.190 4717-4717/ru.ozon.delivery.debug I/Pushwoosh: [s] This is Android FCM device
2020-11-18 09:18:44.802 4717-4806/ru.ozon.delivery.debug D/Pushwoosh: [[BusinessCase]] trigger subscription-segments
2020-11-18 09:18:44.802 4717-4806/ru.ozon.delivery.debug D/Pushwoosh: [[BusinessCase]] trigger push-unregister
2020-11-18 09:18:44.806 4717-4806/ru.ozon.delivery.debug D/Pushwoosh: [BusinessCase] push-unregister condition not satisfied
2020-11-18 09:18:44.814 4717-4717/ru.ozon.delivery.debug D/Pushwoosh: [CrashAnalytics] Current handler class = com.google.firebase.crashlytics.internal.common.CrashlyticsUncaughtExceptionHandler
2020-11-18 09:18:44.831 4717-4798/ru.ozon.delivery.debug D/Pushwoosh: [RequestManager] Try To send: registerUser; baseUrl: https://AAAFF-F8D8B.api.pushwoosh.com/json/1.3/
2020-11-18 09:18:44.832 4717-4806/ru.ozon.delivery.debug D/Pushwoosh: [[BusinessCase]] trigger welcome-inapp
2020-11-18 09:18:44.832 4717-4806/ru.ozon.delivery.debug D/Pushwoosh: [[BusinessCase]] trigger app-update-message
2020-11-18 09:18:44.832 4717-4806/ru.ozon.delivery.debug D/Pushwoosh: [BusinessCase] app-update-message condition not satisfied
2020-11-18 09:18:44.833 4717-4717/ru.ozon.delivery.debug D/Pushwoosh: appOpen:true onAppReady:true
2020-11-18 09:18:44.961 4717-4839/ru.ozon.delivery.debug D/Pushwoosh: [RequestManager] Try To send: getInApps; baseUrl: https://AAAFF-F8D8B.api.pushwoosh.com/json/1.3/
2020-11-18 09:18:45.295 4717-4854/ru.ozon.delivery.debug D/Pushwoosh: [FcmHelper] onTokenRefresh
2020-11-18 09:18:45.346 4717-4839/ru.ozon.delivery.debug I/Pushwoosh: [RequestManager] 
    x
    |     Pushwoosh request:
    | Url: https://AAAFF-F8D8B.api.pushwoosh.com/json/1.3/getInApps
    | Payload: {"request":{"application":"AAAFF-F8D8B","hwid":"a7361663-1788-4e1b-9d60-498841da1db0","v":"5.22.1","device_type":3,"userId":"a7361663-1788-4e1b-9d60-498841da1db0","language":"ru"}}
    | Response: {"status_code":200,"status_message":"OK","response":{"inApps":[]},"base_url":"https:\/\/ozon.pushwoosh.com\/json\/1.3\/"}
    x
2020-11-18 09:18:45.347 4717-4839/ru.ozon.delivery.debug D/Pushwoosh: [RequestManager] getInApps response success
2020-11-18 09:18:45.370 4717-4798/ru.ozon.delivery.debug I/Pushwoosh: [RequestManager] 
    x
    |     Pushwoosh request:
    | Url: https://AAAFF-F8D8B.api.pushwoosh.com/json/1.3/registerUser
    | Payload: {"request":{"application":"AAAFF-F8D8B","hwid":"a7361663-1788-4e1b-9d60-498841da1db0","v":"5.22.1","device_type":3,"userId":"a7361663-1788-4e1b-9d60-498841da1db0"}}
    | Response: {"status_code": 200, "status_message": "OK","response":null}
    x
2020-11-18 09:18:45.370 4717-4798/ru.ozon.delivery.debug D/Pushwoosh: [RequestManager] registerUser response success
2020-11-18 09:18:45.381 4717-4798/ru.ozon.delivery.debug D/Pushwoosh: [RequestManager] Try To send: applicationOpen; baseUrl: https://AAAFF-F8D8B.api.pushwoosh.com/json/1.3/
2020-11-18 09:18:45.563 4717-4798/ru.ozon.delivery.debug I/Pushwoosh: [RequestManager] 
    x
    |     Pushwoosh request:
    | Url: https://AAAFF-F8D8B.api.pushwoosh.com/json/1.3/applicationOpen
    | Payload: {"request":{"application":"AAAFF-F8D8B","hwid":"a7361663-1788-4e1b-9d60-498841da1db0","v":"5.22.1","device_type":3,"userId":"a7361663-1788-4e1b-9d60-498841da1db0","device_name":"Phone","language":"ru","timezone":10800,"android_package":"ru.ozon.delivery.debug","jailbroken":1,"device_model":"Google AOSP on IA Emulator","os_version":"9","app_version":"4.19.2-debug","notificationTypes":6}}
    | Response: {"status_code":200,"status_message":"You have exceeded the amount of active devices allowed on your current subscription plan","response":null,"base_url":"https:\/\/ozon.pushwoosh.com\/json\/1.3\/"}
    x
2020-11-18 09:18:45.565 4717-4798/ru.ozon.delivery.debug D/Pushwoosh: [RequestManager] applicationOpen response success
2020-11-18 09:18:45.733 4717-4854/ru.ozon.delivery.debug E/OzonDeliveryApp$onCreate:     at ru.ozon.delivery.pushservice.data.pushwoosh.PushwooshNotificationManager.sendUpdateToken(PushwooshNotificationManager.kt:54)
2020-11-18 09:18:45.733 4717-4854/ru.ozon.delivery.debug E/OzonDeliveryApp$onCreate:     at ru.ozon.delivery.pushservice.data.pushwoosh.PushwooshNotificationManager.handleNewToken(PushwooshNotificationManager.kt:48)
2020-11-18 09:18:45.746 4717-4798/ru.ozon.delivery.debug D/Pushwoosh: [RequestManager] Try To send: getConfig; baseUrl: https://AAAFF-F8D8B.api.pushwoosh.com/json/1.3/
2020-11-18 09:18:45.910 4717-4798/ru.ozon.delivery.debug I/Pushwoosh: [RequestManager] 
    x
    |     Pushwoosh request:
    | Url: https://AAAFF-F8D8B.api.pushwoosh.com/json/1.3/getConfig
    | Payload: {"request":{"application":"AAAFF-F8D8B","hwid":"a7361663-1788-4e1b-9d60-498841da1db0","v":"5.22.1","device_type":3,"userId":"a7361663-1788-4e1b-9d60-498841da1db0","features":["channels","events"]}}
    | Response: {"status_code":200,"status_message":"OK","response":{"features":{"events":null}}}
    x
2020-11-18 09:18:45.911 4717-4798/ru.ozon.delivery.debug D/Pushwoosh: [RequestManager] getConfig response success
2020-11-18 09:18:48.842 4717-4930/ru.ozon.delivery.debug I/Pushwoosh: [RegistrarWorker] FCM token is cpItaAF4RwOayfGH8_ZP5n:APA91bHlE3l94yg2Pqv21x_-anNOTzLYwY0UBhr87TlGDLlK5Nb648ZyxLKl4FKbvAkgdGo7Y8mXRB0WD-rGZgWd27nOnG1QrdYdSuofqTaFTwvBjPKNDaW52NdlLccRed1Owj0IlECE
2020-11-18 09:18:48.842 4717-4930/ru.ozon.delivery.debug D/Pushwoosh: [DeviceRegistrar] Registering for pushes...
2020-11-18 09:18:48.843 4717-4808/ru.ozon.delivery.debug D/Pushwoosh: [RequestManager] Try To send: registerDevice; baseUrl: https://ozon.pushwoosh.com/json/1.3/
2020-11-18 09:20:04.198 4717-4808/ru.ozon.delivery.debug E/Pushwoosh: [RequestManager] ERROR: Failed to connect to ozon.pushwoosh.com/88.198.209.125:443
    com.pushwoosh.internal.network.b: Failed to connect to ozon.pushwoosh.com/88.198.209.125:443
        at com.pushwoosh.internal.network.e.a(Unknown Source:181)
        at com.pushwoosh.internal.network.e.a(Unknown Source:0)
        at com.pushwoosh.internal.network.e$b.a(Unknown Source:20)
        at com.pushwoosh.internal.network.e$b.doInBackground(Unknown Source:2)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
2020-11-18 09:20:04.199 4717-4717/ru.ozon.delivery.debug E/Pushwoosh: [DeviceRegistrar] Registration error: Failed to connect to ozon.pushwoosh.com/88.198.209.125:443
2020-11-18 09:20:05.598 4717-5435/ru.ozon.delivery.debug E/OzonDeliveryApp$onCreate:     at ru.ozon.delivery.pushservice.data.pushwoosh.PushwooshNotificationManager.sendUpdateToken(PushwooshNotificationManager.kt:54)
2020-11-18 09:20:05.598 4717-5435/ru.ozon.delivery.debug E/OzonDeliveryApp$onCreate:     at ru.ozon.delivery.pushservice.data.pushwoosh.PushwooshNotificationManager.registerPushToken(PushwooshNotificationManager.kt:28)`

Or it problems with our subscription plan?

**Comment by wfhm** [comment] 2020-11-18 06:56
@dyadischevma,

I spoke to our CSM team and they confirmed that the ozon.pushwoosh.com dedicated endpoint was shut down after the account downgrade, and your app still sends requests to it, resulting in timeouts you see in the log. I would suggest creating a support ticket at https://help.pushwoosh.com/hc/en-us/requests/new to resolve this issue. I am closing this one for now as it seems unrelated to the SDK at all.

**Closed by wfhm** 2020-11-18 06:56 UTC
Labels: 54667
